# Generated by Django 2.2.2 on 2019-07-18 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MELIPONARIO', 'Meliponário'), ('APIÁRIO', 'Apiário')], max_length=11)),
                ('qtd_colmeias', models.IntegerField()),
                ('localizacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_perda', models.CharField(choices=[('MORTE POR ABANDONO', 'Morte por abandono'), ('MORTE POR AGROTÓXICO', 'Morte por agrotóxico')], max_length=20)),
                ('qtd_colmeias_perdidas', models.IntegerField()),
                ('data_registro_perda', models.DateTimeField(auto_now_add=True)),
                ('especie_perdida', models.CharField(max_length=255)),
                ('apiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdas', to='bee.Apiario')),
            ],
            options={
                'ordering': ['-data_registro_perda'],
            },
        ),
        migrations.CreateModel(
            name='CaixaRacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=255)),
                ('apiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixas_racionais', to='bee.Apiario')),
            ],
        ),
        migrations.CreateModel(
            name='Apicultor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('qtd_apiarios', models.IntegerField()),
                ('tipo_criador', models.CharField(choices=[('PESQUISADOR', 'Pesquisador'), ('CRIADOR AUTÔNOMO', 'Criador autônomo'), ('PRODUTOR DE MEL', 'Produtor de mel')], max_length=16)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apicultor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apiario',
            name='apicultor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiarios', to='bee.Apicultor'),
        ),
    ]
