# Generated by Django 2.2.2 on 2019-07-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0002_racao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perda',
            name='foto_perda',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perdas'),
        ),
    ]
