# Generated by Django 2.2.2 on 2019-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0006_remove_racao_apicultor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perda',
            name='tipo_perda',
            field=models.CharField(choices=[('POR ABANDONO', 'Abandono de colmeia'), ('POR MORTE', 'Morte por agrotóxico')], max_length=20),
        ),
    ]
